data:
  num_classes: 19
  ignore_label: 255
  training_size: 19132

train:
  seed: 1588147245
  deterministic: True

dataset:
  name: semantic_kitti
  root: /media/wasfy/One Touch1/TA/drive/All/omarwasfy/Master/Thesis/Datasets/dataset/sequences
  num_points: 80000
  voxel_size: 0.05

num_epochs: 15
batch_size: 1

criterion:
  name: cross_entropy
  ignore_index: 255

optimizer:
  name: sgd
  lr: 2.4e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: false

scheduler:
  name: cosine_warmup
